### ISSUE TITLE
haproxy start error as haproxy: line 98: `  $BIN -c -q -f $CFG'

### ISSUE THREAD

**Issue by boyyuan11** [horms/haproxy#2]
I download haproxy-1.6-dev and install on CentOS7, when I try to start haproxy, I get below errors:

haproxy: line 98: syntax error near unexpected token `$BIN'
haproxy: line 98: `  $BIN -c -q -f $CFG'

Finally I find quiet_check() miss a "{" as below:
quiet_check()
  $BIN -c -q -f $CFG
}

So I add "{" for this function, then haproxy runs normal.

**Comment by horms** [comment]
Hi,

On Mon, Apr 27, 2015 at 07:37:33PM -0700, boyyuan11 wrote:
> I download haproxy-1.6-dev and install on CentOS7, when I try to start haproxy, I get below errors:
> 
> haproxy: line 98: syntax error near unexpected token `$BIN'
> haproxy: line 98: `  $BIN -c -q -f $CFG'
> 
> Finally I find quiet_check() miss a "{" as below:
> quiet_check()
>   $BIN -c -q -f $CFG
> }
> 
> So I add "{" for this function, then haproxy runs normal.

I suggest reporting this problem to the haproxy mailing list,
haproxy@formilux.org

**Comment by boyyuan11** [comment]
Hi:
   Thank you.

regards.
